---
- name: Check UFW status
  command: "ufw status"
  register: ufw_status
  changed_when: false


- name: Enable and start ufw
  command: ufw -f enable
  when: "not ufw_status.stdout|search('Status: active')"
